.DEFAULT_GOAL := help

# Override tools as needed, e.g. make lint COMPOSE="docker compose -f docker-compose.yml".
COMPOSE ?= docker compose
UV ?= uv
# Extra pytest arguments and the autogenerated migration's description.
ARGS ?=
MESSAGE ?= migration

.PHONY: help sync lock hooks-install hooks \
	lint fmt type-check security-check check test ci \
	start rebuild stop destroy migrate migrations create-admin seed routes

help: ## Show this help
	@color=; \
	if [ -t 1 ] && [ "$${TERM:-dumb}" != dumb ] && [ -z "$${NO_COLOR:-}" ]; then color=1; fi; \
	awk -v color="$$color" ' \
		BEGIN { \
			FS = ":.*## "; \
			if (color) {bold = "\033[1m"; cyan = "\033[36m"; reset = "\033[0m"} \
			printf "\nUsage:\n  make %s<target>%s\n", cyan, reset \
		} \
		/^##@ / {printf "\n%s%s%s\n", bold, substr($$0, 5), reset} \
		/^[a-zA-Z_-]+:.*## / {printf "  %s%-18s%s %s\n", cyan, $$1, reset, $$2} \
		END {printf "\n"} \
	' $(MAKEFILE_LIST)

##@ Setup
sync: ## Install the locked dependencies
	$(UV) sync --locked

lock: ## Update uv.lock
	$(UV) lock

hooks-install: ## Install the prek Git hook
	$(UV) run --locked prek install

hooks: ## Run prek on all tracked files
	$(UV) run --locked prek run --all-files

##@ Code quality
lint: .state/docker-build-base ## Check Python code with Ruff
	$(COMPOSE) run --rm base bin/lint

fmt: .state/docker-build-base ## Format Python code with Ruff
	$(COMPOSE) run --rm base ruff format .

type-check: .state/docker-build-base ## Check types with ty and pyrefly
	$(COMPOSE) run --rm base ty check cabotage
	$(COMPOSE) run --rm base pyrefly check --error-stale-baseline

security-check: .state/docker-build-base ## Check security with Bandit
	$(COMPOSE) run --rm base bandit -c pyproject.toml -r .

check: lint type-check ## Run lint and type checks

test: .state/docker-build-base ## Run the test suite
	$(COMPOSE) exec -T db psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'cabotage_test'" | grep -q 1 || \
		$(COMPOSE) exec -T db psql -U postgres -c "CREATE DATABASE cabotage_test"
	$(COMPOSE) exec -T db psql -U postgres -d cabotage_test -c "CREATE EXTENSION IF NOT EXISTS citext; CREATE EXTENSION IF NOT EXISTS pgcrypto;"
	$(COMPOSE) run --rm \
		-e CABOTAGE_SQLALCHEMY_DATABASE_URI=postgresql+psycopg://postgres@db/cabotage_test \
		-e CABOTAGE_TESTING=True \
		-e FLASK_APP=cabotage.server.wsgi \
		base sh -c "python3 -m flask db upgrade && python3 -m pytest tests/ -v $(ARGS)"

# Separate recursive calls enforce order and stop on failure, even with make -j.
ci: ## Run lint, fmt, then tests
	$(MAKE) lint
	$(MAKE) fmt
	$(MAKE) test

##@ Development
start: .state/docker-build-base ## Start and seed the stack
	$(COMPOSE) up --detach
	$(MAKE) seed

rebuild: start ## Rebuild the stack as needed

stop: ## Stop the stack; keep its data
	$(COMPOSE) down

destroy: ## Stop the stack and delete its data
	$(COMPOSE) down --volumes

##@ Database and app
migrations: ## Create a migration from model changes
	$(COMPOSE) exec cabotage-app python3 -m flask db revision --autogenerate -m "$(MESSAGE)"

migrate: ## Apply database migrations
	$(COMPOSE) exec cabotage-app python3 -m flask db upgrade

create-admin: ## Create the local admin user
	$(COMPOSE) exec cabotage-app python3 -m cabotage.scripts.create_admin

seed: migrate ## Apply migrations and seed local data
	$(COMPOSE) exec cabotage-app python3 -m cabotage.scripts.seed_localdev

routes: ## List the HTTP routes
	$(COMPOSE) exec cabotage-app python3 -m flask routes

# Cache the development image until its build inputs change.
.state/docker-build-base: Dockerfile pyproject.toml uv.lock package.json bun.lock
	$(COMPOSE) build --force-rm base
	mkdir -p .state
	touch $@
