CREATE ROLE cabotage;
GRANT CONNECT ON DATABASE cabotage_dev to cabotage;
GRANT ALL PRIVILEGES ON DATABASE cabotage_dev TO cabotage;
ALTER DEFAULT PRIVILEGES FOR ROLE cabotage GRANT ALL PRIVILEGES ON TABLES TO cabotage;
ALTER DEFAULT PRIVILEGES FOR ROLE cabotage GRANT ALL PRIVILEGES ON TABLES TO cabotage;
