"""add redis cluster replica counts

Revision ID: 0ccb7fd739a4
Revises: e52e2a058fc3
Create Date: 2026-04-16 14:11:37.045479

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ccb7fd739a4"
down_revision = "e52e2a058fc3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resources_redis", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "leader_replicas", sa.Integer(), server_default="3", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "follower_replicas", sa.Integer(), server_default="3", nullable=False
            )
        )

    with op.batch_alter_table("resources_redis_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "leader_replicas",
                sa.Integer(),
                server_default="3",
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "follower_replicas",
                sa.Integer(),
                server_default="3",
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resources_redis_version", schema=None) as batch_op:
        batch_op.drop_column("follower_replicas")
        batch_op.drop_column("leader_replicas")

    with op.batch_alter_table("resources_redis", schema=None) as batch_op:
        batch_op.drop_column("follower_replicas")
        batch_op.drop_column("leader_replicas")

    # ### end Alembic commands ###
