"""add github repository id

Revision ID: 0da5211f5796
Revises: 25ef379571ff
Create Date: 2026-05-09 18:44:32.623684

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0da5211f5796"
down_revision = "25ef379571ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_applications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("github_repository_id", sa.BigInteger(), nullable=True)
        )

    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "github_repository_id",
                sa.BigInteger(),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.drop_column("github_repository_id")

    with op.batch_alter_table("project_applications", schema=None) as batch_op:
        batch_op.drop_column("github_repository_id")

    # ### end Alembic commands ###
