"""add branch deploy settings

Revision ID: 111eac3110be
Revises: a063138561cc
Create Date: 2026-03-04 21:16:10.771825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '111eac3110be'
down_revision = 'a063138561cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('branch_deploys_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('projects', sa.Column('branch_deploy_base_environment_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_projects_branch_deploy_base_environment_id_project_environments'), 'projects', 'project_environments', ['branch_deploy_base_environment_id'], ['id'])
    op.add_column('projects_version', sa.Column('branch_deploys_enabled', sa.Boolean(), server_default='false', autoincrement=False, nullable=True))
    op.add_column('projects_version', sa.Column('branch_deploy_base_environment_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects_version', 'branch_deploy_base_environment_id')
    op.drop_column('projects_version', 'branch_deploys_enabled')
    op.drop_constraint(op.f('fk_projects_branch_deploy_base_environment_id_project_environments'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'branch_deploy_base_environment_id')
    op.drop_column('projects', 'branch_deploys_enabled')
    # ### end Alembic commands ###
