"""add auto_deploy_wait_for_ci

Revision ID: 14f8def5bd0d
Revises: 84aeacc3bd69
Create Date: 2026-03-19 21:14:09.930139

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "14f8def5bd0d"
down_revision = "84aeacc3bd69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("application_environments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("auto_deploy_wait_for_ci", sa.Boolean(), nullable=True)
        )

    with op.batch_alter_table(
        "application_environments_version", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "auto_deploy_wait_for_ci",
                sa.Boolean(),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "application_environments_version", schema=None
    ) as batch_op:
        batch_op.drop_column("auto_deploy_wait_for_ci")

    with op.batch_alter_table("application_environments", schema=None) as batch_op:
        batch_op.drop_column("auto_deploy_wait_for_ci")

    # ### end Alembic commands ###
