"""

Revision ID: 1f913a84ab35
Revises: 7a4a29016eed
Create Date: 2026-03-29 10:18:37.215628

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1f913a84ab35"
down_revision = "7a4a29016eed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "environment_config_subscriptions_version",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "application_environment_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "environment_configuration_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id",
            "transaction_id",
            name=op.f("pk_environment_config_subscriptions_version"),
        ),
    )
    with op.batch_alter_table(
        "environment_config_subscriptions_version", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_environment_config_subscriptions_version_application_environment_id"
            ),
            ["application_environment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_environment_config_subscriptions_version_end_transaction_id"
            ),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_environment_config_subscriptions_version_environment_configuration_id"
            ),
            ["environment_configuration_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_environment_config_subscriptions_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            "ix_environment_config_subscriptions_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_environment_config_subscriptions_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_environment_config_subscriptions_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "environment_config_subscriptions_version", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_environment_config_subscriptions_version_transaction_id")
        )
        batch_op.drop_index("ix_environment_config_subscriptions_version_pk_validity")
        batch_op.drop_index(
            "ix_environment_config_subscriptions_version_pk_transaction_id"
        )
        batch_op.drop_index(
            batch_op.f("ix_environment_config_subscriptions_version_operation_type")
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_environment_config_subscriptions_version_environment_configuration_id"
            )
        )
        batch_op.drop_index(
            batch_op.f("ix_environment_config_subscriptions_version_end_transaction_id")
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_environment_config_subscriptions_version_application_environment_id"
            )
        )

    op.drop_table("environment_config_subscriptions_version")
    # ### end Alembic commands ###
