"""

Revision ID: 23d40293c277
Revises: 88f230545618
Create Date: 2026-03-24 05:42:34.122435

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "23d40293c277"
down_revision = "88f230545618"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tailscale_integrations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("client_secret_vault_path", sa.String(length=512), nullable=True),
        sa.Column("tailnet", sa.String(length=255), nullable=True),
        sa.Column("default_tags", sa.String(length=512), nullable=True),
        sa.Column("operator_state", sa.String(length=32), nullable=False),
        sa.Column("operator_version", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tailscale_integrations_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tailscale_integrations")),
    )
    with op.batch_alter_table("tailscale_integrations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tailscale_integrations_organization_id"),
            ["organization_id"],
            unique=True,
        )

    with op.batch_alter_table("ingresses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tailscale_hostname", sa.String(length=253), nullable=True)
        )
        batch_op.add_column(sa.Column("tailscale_funnel", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column("tailscale_tags", sa.String(length=512), nullable=True)
        )

    with op.batch_alter_table("ingresses_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tailscale_hostname",
                sa.String(length=253),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "tailscale_funnel", sa.Boolean(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "tailscale_tags",
                sa.String(length=512),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingresses_version", schema=None) as batch_op:
        batch_op.drop_column("tailscale_tags")
        batch_op.drop_column("tailscale_funnel")
        batch_op.drop_column("tailscale_hostname")

    with op.batch_alter_table("ingresses", schema=None) as batch_op:
        batch_op.drop_column("tailscale_tags")
        batch_op.drop_column("tailscale_funnel")
        batch_op.drop_column("tailscale_hostname")

    with op.batch_alter_table("tailscale_integrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tailscale_integrations_organization_id"))

    op.drop_table("tailscale_integrations")
    # ### end Alembic commands ###
