"""add_github_app_installations

Revision ID: 25ef379571ff
Revises: 2b6f8e9621b8
Create Date: 2026-04-30 12:18:35.267661

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "25ef379571ff"
down_revision = "2b6f8e9621b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_applications", schema=None) as batch_op:
        batch_op.alter_column(
            "github_app_installation_id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=True,
        )

    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.alter_column(
            "github_app_installation_id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=True,
            autoincrement=False,
        )

    op.create_table(
        "github_app_installations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=True),
        sa.Column("account_login", sa.String(length=255), nullable=True),
        sa.Column("account_type", sa.String(length=32), nullable=True),
        sa.Column("repository_selection", sa.String(length=32), nullable=True),
        sa.Column(
            "repositories", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("repositories_synced_at", sa.DateTime(), nullable=True),
        sa.Column("installed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installed_by_user_id"],
            ["users.id"],
            name=op.f("fk_github_app_installations_installed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_github_app_installations_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_github_app_installations")),
        sa.UniqueConstraint(
            "organization_id",
            "installation_id",
            name="uq_github_app_installations_org_installation",
        ),
    )
    with op.batch_alter_table("github_app_installations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_github_app_installations_installation_id"),
            ["installation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_github_app_installations_organization_id"),
            ["organization_id"],
            unique=False,
        )

    op.execute(
        """
        INSERT INTO github_app_installations (
            organization_id,
            installation_id,
            created_at,
            updated_at
        )
        SELECT
            projects.organization_id AS organization_id,
            project_applications.github_app_installation_id AS installation_id,
            now() AS created_at,
            now() AS updated_at
        FROM project_applications
        JOIN projects ON projects.id = project_applications.project_id
        WHERE project_applications.github_app_installation_id IS NOT NULL
            AND projects.organization_id IS NOT NULL
        GROUP BY
            projects.organization_id,
            project_applications.github_app_installation_id
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("github_app_installations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_github_app_installations_organization_id"))
        batch_op.drop_index(batch_op.f("ix_github_app_installations_installation_id"))

    op.drop_table("github_app_installations")

    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.alter_column(
            "github_app_installation_id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=True,
            autoincrement=False,
        )

    with op.batch_alter_table("project_applications", schema=None) as batch_op:
        batch_op.alter_column(
            "github_app_installation_id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
    # ### end Alembic commands ###
