"""

Revision ID: 2844ce6b2b04
Revises: b7c9d2e4f6a8
Create Date: 2026-03-19 19:19:18.969731

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2844ce6b2b04"
down_revision = "b7c9d2e4f6a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "branch_deploy_watch_paths",
                postgresql.JSONB(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.drop_column("branch_deploy_watch_paths")

    # ### end Alembic commands ###
