"""add slack discord integrations notification routes with versioning

Revision ID: 28bcc1eb8707
Revises: 5056d1ae059f
Create Date: 2026-04-01 21:18:18.852415

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "28bcc1eb8707"
down_revision = "5056d1ae059f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discord_integrations_version",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("guild_id", sa.String(length=64), autoincrement=False, nullable=True),
        sa.Column(
            "guild_name", sa.String(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "default_channel_id",
            sa.String(length=64),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "default_channel_name",
            sa.String(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "installed_by_user_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("version_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", "transaction_id", name=op.f("pk_discord_integrations_version")
        ),
    )
    with op.batch_alter_table("discord_integrations_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_discord_integrations_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_discord_integrations_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_discord_integrations_version_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_discord_integrations_version_pk_transaction_id",
            ["id", sa.literal_column("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_discord_integrations_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_discord_integrations_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    op.create_table(
        "notification_routes_version",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "notification_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "project_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "environment_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "application_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "integration", sa.String(length=32), autoincrement=False, nullable=True
        ),
        sa.Column(
            "channel_id", sa.String(length=64), autoincrement=False, nullable=True
        ),
        sa.Column(
            "channel_name", sa.String(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("enabled", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("version_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", "transaction_id", name=op.f("pk_notification_routes_version")
        ),
    )
    with op.batch_alter_table("notification_routes_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_routes_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_routes_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_routes_version_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_notification_routes_version_pk_transaction_id",
            ["id", sa.literal_column("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_notification_routes_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_routes_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    op.create_table(
        "slack_integrations_version",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("team_id", sa.String(length=64), autoincrement=False, nullable=True),
        sa.Column(
            "team_name", sa.String(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "bot_user_id", sa.String(length=64), autoincrement=False, nullable=True
        ),
        sa.Column(
            "access_token_vault_path",
            sa.String(length=512),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "default_channel_id",
            sa.String(length=64),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "default_channel_name",
            sa.String(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "installed_by_user_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("version_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", "transaction_id", name=op.f("pk_slack_integrations_version")
        ),
    )
    with op.batch_alter_table("slack_integrations_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_slack_integrations_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_slack_integrations_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_slack_integrations_version_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_slack_integrations_version_pk_transaction_id",
            ["id", sa.literal_column("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_slack_integrations_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_slack_integrations_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    op.create_table(
        "discord_integrations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.String(length=64), nullable=False),
        sa.Column("guild_name", sa.String(length=255), nullable=True),
        sa.Column("default_channel_id", sa.String(length=64), nullable=True),
        sa.Column("default_channel_name", sa.String(length=255), nullable=True),
        sa.Column("installed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installed_by_user_id"],
            ["users.id"],
            name=op.f("fk_discord_integrations_installed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_discord_integrations_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discord_integrations")),
    )
    with op.batch_alter_table("discord_integrations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_discord_integrations_organization_id"),
            ["organization_id"],
            unique=True,
        )

    op.create_table(
        "notification_routes",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "notification_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "project_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "environment_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "application_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("integration", sa.String(length=32), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=False),
        sa.Column("channel_name", sa.String(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notification_routes_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_routes")),
    )
    with op.batch_alter_table("notification_routes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_routes_organization_id"),
            ["organization_id"],
            unique=False,
        )

    op.create_table(
        "slack_integrations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.String(length=64), nullable=False),
        sa.Column("team_name", sa.String(length=255), nullable=True),
        sa.Column("bot_user_id", sa.String(length=64), nullable=True),
        sa.Column("access_token_vault_path", sa.String(length=512), nullable=True),
        sa.Column("default_channel_id", sa.String(length=64), nullable=True),
        sa.Column("default_channel_name", sa.String(length=255), nullable=True),
        sa.Column("installed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installed_by_user_id"],
            ["users.id"],
            name=op.f("fk_slack_integrations_installed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_slack_integrations_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_slack_integrations")),
    )
    with op.batch_alter_table("slack_integrations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_slack_integrations_organization_id"),
            ["organization_id"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("slack_integrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_slack_integrations_organization_id"))

    op.drop_table("slack_integrations")
    with op.batch_alter_table("notification_routes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_routes_organization_id"))

    op.drop_table("notification_routes")
    with op.batch_alter_table("discord_integrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_discord_integrations_organization_id"))

    op.drop_table("discord_integrations")
    with op.batch_alter_table("slack_integrations_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_slack_integrations_version_transaction_id"))
        batch_op.drop_index("ix_slack_integrations_version_pk_validity")
        batch_op.drop_index("ix_slack_integrations_version_pk_transaction_id")
        batch_op.drop_index(batch_op.f("ix_slack_integrations_version_organization_id"))
        batch_op.drop_index(batch_op.f("ix_slack_integrations_version_operation_type"))
        batch_op.drop_index(
            batch_op.f("ix_slack_integrations_version_end_transaction_id")
        )

    op.drop_table("slack_integrations_version")
    with op.batch_alter_table("notification_routes_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_routes_version_transaction_id"))
        batch_op.drop_index("ix_notification_routes_version_pk_validity")
        batch_op.drop_index("ix_notification_routes_version_pk_transaction_id")
        batch_op.drop_index(
            batch_op.f("ix_notification_routes_version_organization_id")
        )
        batch_op.drop_index(batch_op.f("ix_notification_routes_version_operation_type"))
        batch_op.drop_index(
            batch_op.f("ix_notification_routes_version_end_transaction_id")
        )

    op.drop_table("notification_routes_version")
    with op.batch_alter_table("discord_integrations_version", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_discord_integrations_version_transaction_id")
        )
        batch_op.drop_index("ix_discord_integrations_version_pk_validity")
        batch_op.drop_index("ix_discord_integrations_version_pk_transaction_id")
        batch_op.drop_index(
            batch_op.f("ix_discord_integrations_version_organization_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_discord_integrations_version_operation_type")
        )
        batch_op.drop_index(
            batch_op.f("ix_discord_integrations_version_end_transaction_id")
        )

    op.drop_table("discord_integrations_version")
    # ### end Alembic commands ###
