"""add configurable procfile_path to applications

Revision ID: 2b6f8e9621b8
Revises: aa90a43a1737
Create Date: 2026-04-23 17:48:57.059148

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b6f8e9621b8"
down_revision = "aa90a43a1737"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_applications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("procfile_path", sa.Text(), nullable=True))

    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("procfile_path", sa.Text(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.drop_column("procfile_path")

    with op.batch_alter_table("project_applications", schema=None) as batch_op:
        batch_op.drop_column("procfile_path")

    # ### end Alembic commands ###
