"""add environment configurations

Revision ID: 30d4a013f3d3
Revises: dd222c33058e
Create Date: 2026-03-16 23:02:07.286727

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "30d4a013f3d3"
down_revision = "dd222c33058e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_environment_configurations_version",
        sa.Column("created", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "project_id",
            postgresql.UUID(as_uuid=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "environment_id",
            postgresql.UUID(as_uuid=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("name", postgresql.CITEXT(), autoincrement=False, nullable=True),
        sa.Column("value", sa.String(length=2048), autoincrement=False, nullable=True),
        sa.Column("key_slug", sa.Text(), autoincrement=False, nullable=True),
        sa.Column("build_key_slug", sa.Text(), autoincrement=False, nullable=True),
        sa.Column("version_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("deleted", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column("secret", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column("buildtime", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=True
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id",
            "transaction_id",
            name=op.f("pk_project_environment_configurations_version"),
        ),
    )
    op.create_index(
        op.f("ix_project_environment_configurations_version_end_transaction_id"),
        "project_environment_configurations_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_environment_configurations_version_environment_id"),
        "project_environment_configurations_version",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_environment_configurations_version_operation_type"),
        "project_environment_configurations_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_environment_configurations_version_project_id"),
        "project_environment_configurations_version",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_environment_configurations_version_transaction_id"),
        "project_environment_configurations_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "project_environment_configurations",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("environment_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", postgresql.CITEXT(), nullable=False),
        sa.Column("value", sa.String(length=2048), nullable=False),
        sa.Column("key_slug", sa.Text(), nullable=True),
        sa.Column("build_key_slug", sa.Text(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("secret", sa.Boolean(), nullable=False),
        sa.Column("buildtime", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["project_environments.id"],
            name=op.f(
                "fk_project_environment_configurations_environment_id_project_environments"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_environment_configurations_project_id_projects"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_project_environment_configurations")
        ),
        sa.UniqueConstraint(
            "project_id",
            "environment_id",
            "name",
            name="uq_project_env_configurations_project_env_name",
        ),
    )
    op.create_index(
        op.f("ix_project_environment_configurations_environment_id"),
        "project_environment_configurations",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_environment_configurations_project_id"),
        "project_environment_configurations",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "environment_config_subscriptions",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "application_environment_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column(
            "environment_configuration_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_environment_id"],
            ["application_environments.id"],
            name=op.f(
                "fk_environment_config_subscriptions_application_environment_id_application_environments"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["environment_configuration_id"],
            ["project_environment_configurations.id"],
            name=op.f(
                "fk_environment_config_subscriptions_environment_configuration_id_project_environment_configurations"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environment_config_subscriptions")),
        sa.UniqueConstraint(
            "application_environment_id",
            "environment_configuration_id",
            name="uq_env_config_subscription_app_env_config",
        ),
    )
    op.create_index(
        op.f("ix_environment_config_subscriptions_application_environment_id"),
        "environment_config_subscriptions",
        ["application_environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_environment_config_subscriptions_environment_configuration_id"),
        "environment_config_subscriptions",
        ["environment_configuration_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_environment_config_subscriptions_environment_configuration_id"),
        table_name="environment_config_subscriptions",
    )
    op.drop_index(
        op.f("ix_environment_config_subscriptions_application_environment_id"),
        table_name="environment_config_subscriptions",
    )
    op.drop_table("environment_config_subscriptions")
    op.drop_index(
        op.f("ix_project_environment_configurations_project_id"),
        table_name="project_environment_configurations",
    )
    op.drop_index(
        op.f("ix_project_environment_configurations_environment_id"),
        table_name="project_environment_configurations",
    )
    op.drop_table("project_environment_configurations")
    op.drop_index(
        op.f("ix_project_environment_configurations_version_transaction_id"),
        table_name="project_environment_configurations_version",
    )
    op.drop_index(
        op.f("ix_project_environment_configurations_version_project_id"),
        table_name="project_environment_configurations_version",
    )
    op.drop_index(
        op.f("ix_project_environment_configurations_version_operation_type"),
        table_name="project_environment_configurations_version",
    )
    op.drop_index(
        op.f("ix_project_environment_configurations_version_environment_id"),
        table_name="project_environment_configurations_version",
    )
    op.drop_index(
        op.f("ix_project_environment_configurations_version_end_transaction_id"),
        table_name="project_environment_configurations_version",
    )
    op.drop_table("project_environment_configurations_version")
    # ### end Alembic commands ###
