"""add notification_messages table and last_notified_at to alerts

Revision ID: 338509817a34
Revises: 4c69d36e817d
Create Date: 2026-04-02 10:19:09.472484

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "338509817a34"
down_revision = "4c69d36e817d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_messages",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("notification_type", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=False),
        sa.Column("integration", sa.String(length=32), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=False),
        sa.Column("external_message_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notification_messages_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_messages")),
    )
    with op.batch_alter_table("notification_messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_notification_messages_object_lookup",
            ["object_type", "object_id", "integration", "channel_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_messages_organization_id"),
            ["organization_id"],
            unique=False,
        )

    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_notified_at", sa.DateTime(), nullable=True))

    with op.batch_alter_table("alerts_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_notified_at", sa.DateTime(), autoincrement=False, nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerts_version", schema=None) as batch_op:
        batch_op.drop_column("last_notified_at")

    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_column("last_notified_at")

    with op.batch_alter_table("notification_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_messages_organization_id"))
        batch_op.drop_index("ix_notification_messages_object_lookup")

    op.drop_table("notification_messages")
    # ### end Alembic commands ###
