"""add github identities

Revision ID: 3c1dd1e7577c
Revises: 30d4a013f3d3
Create Date: 2026-03-18 18:00:53.525781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c1dd1e7577c'
down_revision = '30d4a013f3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_identities',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(length=255), nullable=False),
    sa.Column('github_access_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_github_identities_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_identities')),
    sa.UniqueConstraint('github_id', name=op.f('uq_github_identities_github_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_github_identities_user_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_identities')
    # ### end Alembic commands ###
