"""add explicit environment namespace mode

Revision ID: 3d08438ad713
Revises: 0ccb7fd739a4
Create Date: 2026-04-16 20:44:20.750320

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d08438ad713"
down_revision = "0ccb7fd739a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_environments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "uses_environment_namespace",
                sa.Boolean(),
                server_default="false",
                nullable=False,
            )
        )

    with op.batch_alter_table("project_environments_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "uses_environment_namespace",
                sa.Boolean(),
                server_default="false",
                autoincrement=False,
                nullable=True,
            )
        )

    op.execute(
        sa.text(
            """
            UPDATE project_environments AS env
            SET uses_environment_namespace = CASE
                WHEN projects.environments_enabled IS NOT TRUE THEN FALSE
                WHEN env.is_default IS TRUE
                     AND EXISTS (
                         SELECT 1
                         FROM application_environments AS ae
                         WHERE ae.environment_id = env.id
                           AND ae.deleted_at IS NULL
                           AND ae.k8s_identifier IS NULL
                     ) THEN FALSE
                ELSE TRUE
            END
            FROM projects
            WHERE projects.id = env.project_id
            """
        )
    )

    op.execute(
        sa.text(
            """
            UPDATE project_environments_version AS env_version
            SET uses_environment_namespace = env.uses_environment_namespace
            FROM project_environments AS env
            WHERE env.id = env_version.id
            """
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_environments_version", schema=None) as batch_op:
        batch_op.drop_column("uses_environment_namespace")

    with op.batch_alter_table("project_environments", schema=None) as batch_op:
        batch_op.drop_column("uses_environment_namespace")

    # ### end Alembic commands ###
