"""empty message

Revision ID: 453e45653299
Revises: fb54812c13a1
Create Date: 2018-03-14 21:34:19.571661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '453e45653299'
down_revision = 'fb54812c13a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hooks',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hooks'))
    )
    op.create_table('hooks_version',
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_hooks_version'))
    )
    op.create_index(op.f('ix_hooks_version_end_transaction_id'), 'hooks_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_hooks_version_operation_type'), 'hooks_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_hooks_version_transaction_id'), 'hooks_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hooks_version_transaction_id'), table_name='hooks_version')
    op.drop_index(op.f('ix_hooks_version_operation_type'), table_name='hooks_version')
    op.drop_index(op.f('ix_hooks_version_end_transaction_id'), table_name='hooks_version')
    op.drop_table('hooks_version')
    op.drop_table('hooks')
    # ### end Alembic commands ###
