"""add application_id indexes and audit_log view

Revision ID: 484a6a1954ea
Revises: ad75e4f600d2
Create Date: 2026-03-28 21:06:50.642248

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "484a6a1954ea"
down_revision = "ad75e4f600d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deployments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deployments_application_id"),
            ["application_id"],
            unique=False,
        )

    with op.batch_alter_table("deployments_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deployments_version_application_id"),
            ["application_id"],
            unique=False,
        )

    with op.batch_alter_table("project_app_configurations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_app_configurations_application_id"),
            ["application_id"],
            unique=False,
        )

    with op.batch_alter_table(
        "project_app_configurations_version", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_app_configurations_version_application_id"),
            ["application_id"],
            unique=False,
        )

    with op.batch_alter_table("project_app_images", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_app_images_application_id"),
            ["application_id"],
            unique=False,
        )

    with op.batch_alter_table("project_app_images_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_app_images_version_application_id"),
            ["application_id"],
            unique=False,
        )

    with op.batch_alter_table("project_app_releases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_app_releases_application_id"),
            ["application_id"],
            unique=False,
        )

    with op.batch_alter_table("project_app_releases_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_app_releases_version_application_id"),
            ["application_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_app_releases_version", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_project_app_releases_version_application_id")
        )

    with op.batch_alter_table("project_app_releases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_app_releases_application_id"))

    with op.batch_alter_table("project_app_images_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_app_images_version_application_id"))

    with op.batch_alter_table("project_app_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_app_images_application_id"))

    with op.batch_alter_table(
        "project_app_configurations_version", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_project_app_configurations_version_application_id")
        )

    with op.batch_alter_table("project_app_configurations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_app_configurations_application_id"))

    with op.batch_alter_table("deployments_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deployments_version_application_id"))

    with op.batch_alter_table("deployments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deployments_application_id"))

    # ### end Alembic commands ###
