"""add alerts table with versioning

Revision ID: 5056d1ae059f
Revises: 1f913a84ab35
Create Date: 2026-03-30 21:11:44.838069

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5056d1ae059f"
down_revision = "1f913a84ab35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts_version",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "fingerprint", sa.String(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("status", sa.String(length=32), autoincrement=False, nullable=True),
        sa.Column(
            "alertname", sa.String(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "labels",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "annotations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("starts_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("ends_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("generator_url", sa.Text(), autoincrement=False, nullable=True),
        sa.Column("group_key", sa.Text(), autoincrement=False, nullable=True),
        sa.Column(
            "receiver", sa.String(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("application_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "application_environment_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column("version_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("created", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id", name=op.f("pk_alerts_version")),
    )
    with op.batch_alter_table("alerts_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_alerts_version_alertname"), ["alertname"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_version_application_environment_id"),
            ["application_environment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_version_application_id"),
            ["application_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_version_end_transaction_id"),
            ["end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_version_fingerprint"), ["fingerprint"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_version_operation_type"),
            ["operation_type"],
            unique=False,
        )
        batch_op.create_index(
            "ix_alerts_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_alerts_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_version_starts_at"), ["starts_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_version_transaction_id"),
            ["transaction_id"],
            unique=False,
        )

    op.create_table(
        "alerts",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("fingerprint", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("alertname", sa.String(length=256), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "annotations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("generator_url", sa.Text(), nullable=True),
        sa.Column("group_key", sa.Text(), nullable=True),
        sa.Column("receiver", sa.String(length=256), nullable=True),
        sa.Column("application_id", sa.UUID(), nullable=True),
        sa.Column("application_environment_id", sa.UUID(), nullable=True),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_environment_id"],
            ["application_environments.id"],
            name=op.f("fk_alerts_application_environment_id_application_environments"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["project_applications.id"],
            name=op.f("fk_alerts_application_id_project_applications"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_alerts_alertname"), ["alertname"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_application_environment_id"),
            ["application_environment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_fingerprint"), ["fingerprint"], unique=False
        )
        batch_op.create_index(
            "ix_alerts_fingerprint_starts_at", ["fingerprint", "starts_at"], unique=True
        )
        batch_op.create_index(
            "ix_alerts_fingerprint_status", ["fingerprint", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_starts_at"), ["starts_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_starts_at"))
        batch_op.drop_index("ix_alerts_fingerprint_status")
        batch_op.drop_index("ix_alerts_fingerprint_starts_at")
        batch_op.drop_index(batch_op.f("ix_alerts_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_alerts_application_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_application_environment_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_alertname"))

    op.drop_table("alerts")
    with op.batch_alter_table("alerts_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_version_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_version_starts_at"))
        batch_op.drop_index("ix_alerts_version_pk_validity")
        batch_op.drop_index("ix_alerts_version_pk_transaction_id")
        batch_op.drop_index(batch_op.f("ix_alerts_version_operation_type"))
        batch_op.drop_index(batch_op.f("ix_alerts_version_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_alerts_version_end_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_version_application_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_version_application_environment_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_version_alertname"))

    op.drop_table("alerts_version")
    # ### end Alembic commands ###
