"""empty message

Revision ID: 6b6caf399b71
Revises: e11c61ce67e7
Create Date: 2019-02-01 20:41:05.731909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6caf399b71'
down_revision = 'e11c61ce67e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_applications', sa.Column('auto_deploy_branch', sa.Text(), nullable=True))
    op.add_column('project_applications', sa.Column('github_repository', sa.Text(), nullable=True))
    op.add_column('project_applications_version', sa.Column('auto_deploy_branch', sa.Text(), autoincrement=False, nullable=True))
    op.add_column('project_applications_version', sa.Column('github_repository', sa.Text(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_applications_version', 'github_repository')
    op.drop_column('project_applications_version', 'auto_deploy_branch')
    op.drop_column('project_applications', 'github_repository')
    op.drop_column('project_applications', 'auto_deploy_branch')
    # ### end Alembic commands ###
