"""add organization requests

Revision ID: 6e1f85c42b83
Revises: 0da5211f5796
Create Date: 2026-05-17 23:12:25.930162

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6e1f85c42b83"
down_revision = "0da5211f5796"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_requests",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("requester_user_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_user_id", sa.UUID(), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_requests_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["requester_user_id"],
            ["users.id"],
            name=op.f("fk_organization_requests_requester_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
            name=op.f("fk_organization_requests_reviewer_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_requests")),
    )
    with op.batch_alter_table("organization_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organization_requests_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_organization_requests_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_organization_requests_requester_user_id"),
            ["requester_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_organization_requests_reviewer_user_id"),
            ["reviewer_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_organization_requests_slug"), ["slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_organization_requests_status"), ["status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organization_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organization_requests_status"))
        batch_op.drop_index(batch_op.f("ix_organization_requests_slug"))
        batch_op.drop_index(batch_op.f("ix_organization_requests_reviewer_user_id"))
        batch_op.drop_index(batch_op.f("ix_organization_requests_requester_user_id"))
        batch_op.drop_index(batch_op.f("ix_organization_requests_organization_id"))
        batch_op.drop_index(batch_op.f("ix_organization_requests_created_at"))

    op.drop_table("organization_requests")
    # ### end Alembic commands ###
