"""

Revision ID: 6e316a9c6aaf
Revises: 2cef85139932
Create Date: 2026-03-23 02:40:44.054827

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "6e316a9c6aaf"
down_revision = "2cef85139932"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tailscale_integrations", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_tailscale_integrations_organization_id", type_="unique"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tailscale_integrations", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_tailscale_integrations_organization_id",
            ["organization_id"],
            postgresql_nulls_not_distinct=False,
        )

    # ### end Alembic commands ###
