"""empty message

Revision ID: 732af5abd4a6
Revises: a63d44abfe31
Create Date: 2023-02-11 18:42:50.095116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "732af5abd4a6"
down_revision = "a63d44abfe31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "github_deployments_unique",
        "project_applications",
        ["github_app_installation_id", "github_repository", "github_environment_name"],
        unique=True,
        postgresql_where=sa.text("github_environment_name IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "github_deployments_unique",
        table_name="project_applications",
        postgresql_where=sa.text("github_environment_name IS NOT NULL"),
    )
    # ### end Alembic commands ###
