"""

Revision ID: 786a1c6b2ecf
Revises: a1b2c3d4e5f6
Create Date: 2026-03-02 22:48:35.458942

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "786a1c6b2ecf"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resources_redis")
    op.drop_index(
        "ix_resources_certificate_version_end_transaction_id",
        table_name="resources_certificate_version",
    )
    op.drop_index(
        "ix_resources_certificate_version_operation_type",
        table_name="resources_certificate_version",
    )
    op.drop_index(
        "ix_resources_certificate_version_transaction_id",
        table_name="resources_certificate_version",
    )
    op.drop_table("resources_certificate_version")
    op.drop_index(
        "ix_resources_version_end_transaction_id", table_name="resources_version"
    )
    op.drop_index("ix_resources_version_operation_type", table_name="resources_version")
    op.drop_index("ix_resources_version_transaction_id", table_name="resources_version")
    op.drop_table("resources_version")
    op.drop_index(
        "ix_resources_postgres_version_end_transaction_id",
        table_name="resources_postgres_version",
    )
    op.drop_index(
        "ix_resources_postgres_version_operation_type",
        table_name="resources_postgres_version",
    )
    op.drop_index(
        "ix_resources_postgres_version_transaction_id",
        table_name="resources_postgres_version",
    )
    op.drop_table("resources_postgres_version")
    op.drop_table("resources_ingress")
    op.drop_table("resources_certificate")
    op.drop_index(
        "ix_resources_redis_version_end_transaction_id",
        table_name="resources_redis_version",
    )
    op.drop_index(
        "ix_resources_redis_version_operation_type",
        table_name="resources_redis_version",
    )
    op.drop_index(
        "ix_resources_redis_version_transaction_id",
        table_name="resources_redis_version",
    )
    op.drop_table("resources_redis_version")
    op.drop_index(
        "ix_resources_ingress_version_end_transaction_id",
        table_name="resources_ingress_version",
    )
    op.drop_index(
        "ix_resources_ingress_version_operation_type",
        table_name="resources_ingress_version",
    )
    op.drop_index(
        "ix_resources_ingress_version_transaction_id",
        table_name="resources_ingress_version",
    )
    op.drop_table("resources_ingress_version")
    op.drop_table("resources_postgres")
    op.drop_table("resources")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resources",
        sa.Column(
            "created", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id",
            postgresql.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "application_id", postgresql.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["project_applications.id"],
            name="fk_resources_application_id_project_applications",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_resources"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "resources_postgres",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["resources.id"], name="fk_resources_postgres_id_resources"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_resources_postgres"),
    )
    op.create_table(
        "resources_ingress_version",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "end_transaction_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("operation_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint(
            "id", "transaction_id", name="pk_resources_ingress_version"
        ),
    )
    op.create_index(
        "ix_resources_ingress_version_transaction_id",
        "resources_ingress_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        "ix_resources_ingress_version_operation_type",
        "resources_ingress_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        "ix_resources_ingress_version_end_transaction_id",
        "resources_ingress_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_table(
        "resources_redis_version",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "end_transaction_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("operation_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint(
            "id", "transaction_id", name="pk_resources_redis_version"
        ),
    )
    op.create_index(
        "ix_resources_redis_version_transaction_id",
        "resources_redis_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        "ix_resources_redis_version_operation_type",
        "resources_redis_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        "ix_resources_redis_version_end_transaction_id",
        "resources_redis_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_table(
        "resources_certificate",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["resources.id"], name="fk_resources_certificate_id_resources"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_resources_certificate"),
    )
    op.create_table(
        "resources_ingress",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["resources.id"], name="fk_resources_ingress_id_resources"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_resources_ingress"),
    )
    op.create_table(
        "resources_postgres_version",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "end_transaction_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("operation_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint(
            "id", "transaction_id", name="pk_resources_postgres_version"
        ),
    )
    op.create_index(
        "ix_resources_postgres_version_transaction_id",
        "resources_postgres_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        "ix_resources_postgres_version_operation_type",
        "resources_postgres_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        "ix_resources_postgres_version_end_transaction_id",
        "resources_postgres_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_table(
        "resources_version",
        sa.Column(
            "created", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "id",
            postgresql.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "application_id", postgresql.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "end_transaction_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("operation_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id", name="pk_resources_version"),
    )
    op.create_index(
        "ix_resources_version_transaction_id",
        "resources_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        "ix_resources_version_operation_type",
        "resources_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        "ix_resources_version_end_transaction_id",
        "resources_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_table(
        "resources_certificate_version",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("transaction_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "end_transaction_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column("operation_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint(
            "id", "transaction_id", name="pk_resources_certificate_version"
        ),
    )
    op.create_index(
        "ix_resources_certificate_version_transaction_id",
        "resources_certificate_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        "ix_resources_certificate_version_operation_type",
        "resources_certificate_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        "ix_resources_certificate_version_end_transaction_id",
        "resources_certificate_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_table(
        "resources_redis",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["resources.id"], name="fk_resources_redis_id_resources"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_resources_redis"),
    )
    # ### end Alembic commands ###
