"""add job_logs table

Revision ID: 7a4a29016eed
Revises: 5db73750bd83
Create Date: 2026-03-27 18:54:48.914536

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7a4a29016eed"
down_revision = "5db73750bd83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_logs",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("application_environment_id", sa.UUID(), nullable=False),
        sa.Column("process_name", sa.String(length=64), nullable=False),
        sa.Column("job_name", sa.String(length=253), nullable=False),
        sa.Column("namespace", sa.String(length=253), nullable=False),
        sa.Column("schedule_timestamp", sa.DateTime(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("completion_time", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("pods_active", sa.Integer(), nullable=False),
        sa.Column("pods_succeeded", sa.Integer(), nullable=False),
        sa.Column("pods_failed", sa.Integer(), nullable=False),
        sa.Column("release_version", sa.Integer(), nullable=True),
        sa.Column("deployment_id", sa.String(length=64), nullable=True),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_environment_id"],
            ["application_environments.id"],
            name=op.f(
                "fk_job_logs_application_environment_id_application_environments"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["project_applications.id"],
            name=op.f("fk_job_logs_application_id_project_applications"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_logs")),
        sa.UniqueConstraint("job_name", name=op.f("uq_job_logs_job_name")),
    )
    with op.batch_alter_table("job_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_logs_application_environment_id"),
            ["application_environment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_job_logs_application_id"), ["application_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_logs_application_id"))
        batch_op.drop_index(batch_op.f("ix_job_logs_application_environment_id"))

    op.drop_table("job_logs")
    # ### end Alembic commands ###
