"""empty message

Revision ID: 7be3d140b38b
Revises: 99b7ba46239d
Create Date: 2018-03-14 08:47:51.323112

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7be3d140b38b"
down_revision = "99b7ba46239d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deployments", sa.Column("complete", sa.Boolean(), nullable=False))
    op.add_column("deployments", sa.Column("deploy_log", sa.Text(), nullable=True))
    op.add_column("deployments", sa.Column("error", sa.Boolean(), nullable=False))
    op.add_column(
        "deployments", sa.Column("error_detail", sa.String(length=2048), nullable=True)
    )
    op.add_column(
        "deployments_version",
        sa.Column("complete", sa.Boolean(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "deployments_version",
        sa.Column("deploy_log", sa.Text(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "deployments_version",
        sa.Column("error", sa.Boolean(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "deployments_version",
        sa.Column(
            "error_detail", sa.String(length=2048), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deployments_version", "error_detail")
    op.drop_column("deployments_version", "error")
    op.drop_column("deployments_version", "deploy_log")
    op.drop_column("deployments_version", "complete")
    op.drop_column("deployments", "error_detail")
    op.drop_column("deployments", "error")
    op.drop_column("deployments", "deploy_log")
    op.drop_column("deployments", "complete")
    # ### end Alembic commands ###
