"""make notification_messages object lookup unique

Revision ID: 7d2b3c334ed4
Revises: 338509817a34
Create Date: 2026-04-03 11:50:58.422306

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d2b3c334ed4"
down_revision = "338509817a34"
branch_labels = None
depends_on = None


def upgrade():
    # Remove duplicate rows before adding unique constraint, keeping the
    # most recently updated row for each (object_type, object_id,
    # integration, channel_id) tuple.
    op.execute(
        sa.text("""
        DELETE FROM notification_messages
        WHERE id NOT IN (
            SELECT DISTINCT ON (object_type, object_id, integration, channel_id) id
            FROM notification_messages
            ORDER BY object_type, object_id, integration, channel_id, updated_at DESC
        )
    """)
    )

    with op.batch_alter_table("notification_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_messages_object_lookup"))
        batch_op.create_index(
            "ix_notification_messages_object_lookup",
            ["object_type", "object_id", "integration", "channel_id"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_notification_messages_object_lookup")
        batch_op.create_index(
            batch_op.f("ix_notification_messages_object_lookup"),
            ["object_type", "object_id", "integration", "channel_id"],
            unique=False,
        )

    # ### end Alembic commands ###
