"""change storage_size to integer

Revision ID: 7e334b3e2b87
Revises: f7ba2e49c737
Create Date: 2026-04-12 16:45:50.272831

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7e334b3e2b87"
down_revision = "f7ba2e49c737"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        sa.text(
            "ALTER TABLE resources "
            "ALTER COLUMN storage_size TYPE INTEGER "
            "USING CAST(regexp_replace(storage_size, '[^0-9]', '', 'g') AS INTEGER)"
        )
    )
    op.execute(
        sa.text(
            "ALTER TABLE resources_version "
            "ALTER COLUMN storage_size TYPE INTEGER "
            "USING CAST(regexp_replace(storage_size, '[^0-9]', '', 'g') AS INTEGER)"
        )
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resources_version", schema=None) as batch_op:
        batch_op.alter_column(
            "storage_size",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=16),
            existing_nullable=True,
            autoincrement=False,
        )

    with op.batch_alter_table("resources", schema=None) as batch_op:
        batch_op.alter_column(
            "storage_size",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=16),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
