"""

Revision ID: 7fa8cc9ad1c2
Revises: 088fc773e9fe
Create Date: 2025-01-15 18:27:04.152781

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7fa8cc9ad1c2"
down_revision = "088fc773e9fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("grafana_org_id", sa.Integer(), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_organizations_grafana_org_id"), "organizations", ["grafana_org_id"]
    )
    op.add_column(
        "organizations_version",
        sa.Column("grafana_org_id", sa.Integer(), autoincrement=False, nullable=True),
    )
    op.add_column("projects", sa.Column("grafana_team_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(
        op.f("uq_projects_grafana_team_id"), "projects", ["grafana_team_id"]
    )
    op.add_column(
        "projects_version",
        sa.Column("grafana_team_id", sa.Integer(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users", sa.Column("grafana_jwt", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users_version",
        sa.Column(
            "grafana_jwt", sa.String(length=255), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations_version", "grafana_org_id")
    op.drop_constraint(
        op.f("uq_organizations_grafana_org_id"), "organizations", type_="unique"
    )
    op.drop_column("organizations", "grafana_org_id")
    op.drop_column("users_version", "grafana_jwt")
    op.drop_column("users", "grafana_jwt")
    op.drop_column("projects_version", "grafana_team_id")
    op.drop_constraint(op.f("uq_projects_grafana_team_id"), "projects", type_="unique")
    op.drop_column("projects", "grafana_team_id")
    # ### end Alembic commands ###
