"""add branch_deploy_watch_paths and auto_deploy_wait_for_ci

Revision ID: 84aeacc3bd69
Revises: 2844ce6b2b04
Create Date: 2026-03-19 20:55:32.628213

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "84aeacc3bd69"
down_revision = "2844ce6b2b04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_applications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "auto_deploy_wait_for_ci",
                sa.Boolean(),
                server_default="true",
                nullable=False,
            )
        )

    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "auto_deploy_wait_for_ci",
                sa.Boolean(),
                server_default="true",
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.drop_column("auto_deploy_wait_for_ci")

    with op.batch_alter_table("project_applications", schema=None) as batch_op:
        batch_op.drop_column("auto_deploy_wait_for_ci")

    # ### end Alembic commands ###
