"""

Revision ID: 88f230545618
Revises: f40dfa811074
Create Date: 2026-03-20 16:26:53.459573

"""

from alembic import op
import flask_security
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "88f230545618"
down_revision = "f40dfa811074"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webauthn",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(length=1024), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=True),
        sa.Column("transports", flask_security.datastore.AsaList(), nullable=True),
        sa.Column("backup_state", sa.Boolean(), nullable=False),
        sa.Column("device_type", sa.String(length=64), nullable=False),
        sa.Column("extensions", sa.String(length=255), nullable=True),
        sa.Column(
            "create_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lastuse_datetime", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("usage", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_webauthn_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webauthn")),
    )
    with op.batch_alter_table("webauthn", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webauthn_credential_id"), ["credential_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webauthn", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webauthn_credential_id"))

    op.drop_table("webauthn")
    # ### end Alembic commands ###
