"""fix ingress version table nullability

Revision ID: 97ead80e7ae6
Revises: a95f942c7d60
Create Date: 2026-03-09 23:37:01.845078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97ead80e7ae6'
down_revision = 'a95f942c7d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingress_hosts_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'ingress_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'hostname',
               existing_type=sa.VARCHAR(length=253),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'tls_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'is_auto_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'ingress_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'path',
               existing_type=sa.VARCHAR(length=256),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'path_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'target_process_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'application_environment_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'ingress_class_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'backend_protocol',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'session_affinity',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'use_regex',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'allow_annotations',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'extra_annotations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               autoincrement=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ingresses_version', 'cluster_issuer',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'force_ssl_redirect',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'service_upstream',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               autoincrement=False)
    op.alter_column('ingresses_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingresses_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'service_upstream',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'force_ssl_redirect',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'cluster_issuer',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'extra_annotations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               autoincrement=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ingresses_version', 'allow_annotations',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'use_regex',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'session_affinity',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'backend_protocol',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'ingress_class_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'application_environment_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingresses_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'target_process_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'path_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'path',
               existing_type=sa.VARCHAR(length=256),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'ingress_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_paths_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'is_auto_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'tls_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'hostname',
               existing_type=sa.VARCHAR(length=253),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'ingress_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    op.alter_column('ingress_hosts_version', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
