"""add environments

Revision ID: a063138561cc
Revises: b4e7f8a9c0d1
Create Date: 2026-03-03 15:33:56.450224

"""
from alembic import op
import citext
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a063138561cc'
down_revision = 'b4e7f8a9c0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_environments_version',
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('application_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True),
    sa.Column('environment_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True),
    sa.Column('process_counts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("json_object('{}')"), autoincrement=False, nullable=True),
    sa.Column('process_pod_classes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("json_object('{}')"), autoincrement=False, nullable=True),
    sa.Column('deployment_timeout', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('health_check_path', sa.String(length=64), autoincrement=False, nullable=True),
    sa.Column('health_check_host', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('auto_deploy_branch', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('github_environment_name', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_application_environments_version'))
    )
    op.create_index(op.f('ix_application_environments_version_end_transaction_id'), 'application_environments_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_application_environments_version_operation_type'), 'application_environments_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_application_environments_version_transaction_id'), 'application_environments_version', ['transaction_id'], unique=False)
    op.create_table('project_environments_version',
    sa.Column('created', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True),
    sa.Column('name', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('slug', citext.CIText(), autoincrement=False, nullable=True),
    sa.Column('k8s_identifier', sa.String(length=64), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('ephemeral', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('ttl_hours', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_project_environments_version'))
    )
    op.create_index(op.f('ix_project_environments_version_end_transaction_id'), 'project_environments_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_project_environments_version_operation_type'), 'project_environments_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_project_environments_version_transaction_id'), 'project_environments_version', ['transaction_id'], unique=False)
    op.create_table('project_environments',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', citext.CIText(), nullable=False),
    sa.Column('k8s_identifier', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('ephemeral', sa.Boolean(), nullable=False),
    sa.Column('ttl_hours', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_environments_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_environments')),
    sa.UniqueConstraint('project_id', 'k8s_identifier', name='uq_project_environments_project_k8s_identifier'),
    sa.UniqueConstraint('project_id', 'slug', name=op.f('uq_project_environments_project_id'))
    )
    op.create_table('application_environments',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('environment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('process_counts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("json_object('{}')"), nullable=True),
    sa.Column('process_pod_classes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("json_object('{}')"), nullable=True),
    sa.Column('deployment_timeout', sa.Integer(), nullable=True),
    sa.Column('health_check_path', sa.String(length=64), nullable=True),
    sa.Column('health_check_host', sa.String(length=256), nullable=True),
    sa.Column('auto_deploy_branch', sa.Text(), nullable=True),
    sa.Column('github_environment_name', sa.Text(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['project_applications.id'], name=op.f('fk_application_environments_application_id_project_applications')),
    sa.ForeignKeyConstraint(['environment_id'], ['project_environments.id'], name=op.f('fk_application_environments_environment_id_project_environments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_environments')),
    sa.UniqueConstraint('application_id', 'environment_id', name=op.f('uq_application_environments_application_id'))
    )
    op.add_column('deployments', sa.Column('application_environment_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_deployments_application_environment_id_application_environments'), 'deployments', 'application_environments', ['application_environment_id'], ['id'])
    op.add_column('deployments_version', sa.Column('application_environment_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True))
    op.add_column('project_app_configurations', sa.Column('application_environment_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('uq_project_app_configurations_application_id', 'project_app_configurations', type_='unique')
    op.create_unique_constraint('uq_project_app_configurations_app_env_name', 'project_app_configurations', ['application_id', 'application_environment_id', 'name'])
    op.create_index('uq_project_app_configurations_app_name_no_env', 'project_app_configurations', ['application_id', 'name'], unique=True, postgresql_where=sa.text('application_environment_id IS NULL'))
    op.create_foreign_key(op.f('fk_project_app_configurations_application_environment_id_application_environments'), 'project_app_configurations', 'application_environments', ['application_environment_id'], ['id'])
    op.add_column('project_app_configurations_version', sa.Column('application_environment_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True))
    op.add_column('project_app_images', sa.Column('application_environment_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_project_app_images_application_environment_id_application_environments'), 'project_app_images', 'application_environments', ['application_environment_id'], ['id'])
    op.add_column('project_app_images_version', sa.Column('application_environment_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True))
    op.add_column('project_app_releases', sa.Column('application_environment_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_project_app_releases_application_environment_id_application_environments'), 'project_app_releases', 'application_environments', ['application_environment_id'], ['id'])
    op.add_column('project_app_releases_version', sa.Column('application_environment_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('environments_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('projects_version', sa.Column('environments_enabled', sa.Boolean(), server_default='false', autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects_version', 'environments_enabled')
    op.drop_column('projects', 'environments_enabled')
    op.drop_column('project_app_releases_version', 'application_environment_id')
    op.drop_constraint(op.f('fk_project_app_releases_application_environment_id_application_environments'), 'project_app_releases', type_='foreignkey')
    op.drop_column('project_app_releases', 'application_environment_id')
    op.drop_column('project_app_images_version', 'application_environment_id')
    op.drop_constraint(op.f('fk_project_app_images_application_environment_id_application_environments'), 'project_app_images', type_='foreignkey')
    op.drop_column('project_app_images', 'application_environment_id')
    op.drop_column('project_app_configurations_version', 'application_environment_id')
    op.drop_constraint(op.f('fk_project_app_configurations_application_environment_id_application_environments'), 'project_app_configurations', type_='foreignkey')
    op.drop_index('uq_project_app_configurations_app_name_no_env', table_name='project_app_configurations', postgresql_where=sa.text('application_environment_id IS NULL'))
    op.drop_constraint('uq_project_app_configurations_app_env_name', 'project_app_configurations', type_='unique')
    op.create_unique_constraint('uq_project_app_configurations_application_id', 'project_app_configurations', ['application_id', 'name'])
    op.drop_column('project_app_configurations', 'application_environment_id')
    op.drop_column('deployments_version', 'application_environment_id')
    op.drop_constraint(op.f('fk_deployments_application_environment_id_application_environments'), 'deployments', type_='foreignkey')
    op.drop_column('deployments', 'application_environment_id')
    op.drop_table('application_environments')
    op.drop_table('project_environments')
    op.drop_index(op.f('ix_project_environments_version_transaction_id'), table_name='project_environments_version')
    op.drop_index(op.f('ix_project_environments_version_operation_type'), table_name='project_environments_version')
    op.drop_index(op.f('ix_project_environments_version_end_transaction_id'), table_name='project_environments_version')
    op.drop_table('project_environments_version')
    op.drop_index(op.f('ix_application_environments_version_transaction_id'), table_name='application_environments_version')
    op.drop_index(op.f('ix_application_environments_version_operation_type'), table_name='application_environments_version')
    op.drop_index(op.f('ix_application_environments_version_end_transaction_id'), table_name='application_environments_version')
    op.drop_table('application_environments_version')
    # ### end Alembic commands ###
