"""

Revision ID: a1180f9d5950
Revises: 088fc773e9fe
Create Date: 2025-01-22 13:55:56.807342

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a1180f9d5950"
down_revision = "088fc773e9fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_applications",
        sa.Column(
            "process_ingresses",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("json_object('{}')"),
            nullable=True,
        ),
    )
    op.add_column(
        "project_applications_version",
        sa.Column(
            "process_ingresses",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("json_object('{}')"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_applications_version", "process_ingresses")
    op.drop_column("project_applications", "process_ingresses")
    # ### end Alembic commands ###
