"""

Revision ID: a5088485aa53
Revises: f0735497b1aa
Create Date: 2026-03-17 09:27:55.312294

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a5088485aa53"
down_revision = "f0735497b1aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "application_environments_version", schema=None
    ) as batch_op:
        batch_op.create_index(
            "ix_application_environments_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_application_environments_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("deployments_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_deployments_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_deployments_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("hooks_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_hooks_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_hooks_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("ingress_hosts_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ingress_hosts_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_ingress_hosts_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("ingress_paths_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ingress_paths_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_ingress_paths_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("ingresses_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_ingresses_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_ingresses_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("organizations_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_organizations_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_organizations_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table(
        "project_app_configurations_version", schema=None
    ) as batch_op:
        batch_op.create_index(
            "ix_project_app_configurations_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_project_app_configurations_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("project_app_images_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_project_app_images_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_project_app_images_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("project_app_releases_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_project_app_releases_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_project_app_releases_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_project_applications_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_project_applications_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table(
        "project_environment_configurations_version", schema=None
    ) as batch_op:
        batch_op.create_index(
            "ix_project_environment_configurations_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_project_environment_configurations_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("project_environments_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_project_environments_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_project_environments_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("projects_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_projects_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_projects_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("roles_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_roles_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_roles_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("teams_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_teams_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_teams_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "last_login_ip",
            existing_type=postgresql.INET(),
            type_=sa.String(length=64),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "current_login_ip",
            existing_type=postgresql.INET(),
            type_=sa.String(length=64),
            existing_nullable=True,
        )

    with op.batch_alter_table("users_version", schema=None) as batch_op:
        batch_op.alter_column(
            "last_login_ip",
            existing_type=postgresql.INET(),
            type_=sa.String(length=64),
            existing_nullable=True,
            autoincrement=False,
        )
        batch_op.alter_column(
            "current_login_ip",
            existing_type=postgresql.INET(),
            type_=sa.String(length=64),
            existing_nullable=True,
            autoincrement=False,
        )
        batch_op.create_index(
            "ix_users_version_pk_transaction_id",
            ["id", sa.text("transaction_id DESC")],
            unique=False,
        )
        batch_op.create_index(
            "ix_users_version_pk_validity",
            ["id", "transaction_id", "end_transaction_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users_version", schema=None) as batch_op:
        batch_op.drop_index("ix_users_version_pk_validity")
        batch_op.drop_index("ix_users_version_pk_transaction_id")
        batch_op.alter_column(
            "current_login_ip",
            existing_type=sa.String(length=64),
            type_=postgresql.INET(),
            existing_nullable=True,
            autoincrement=False,
        )
        batch_op.alter_column(
            "last_login_ip",
            existing_type=sa.String(length=64),
            type_=postgresql.INET(),
            existing_nullable=True,
            autoincrement=False,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "current_login_ip",
            existing_type=sa.String(length=64),
            type_=postgresql.INET(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "last_login_ip",
            existing_type=sa.String(length=64),
            type_=postgresql.INET(),
            existing_nullable=True,
        )

    with op.batch_alter_table("teams_version", schema=None) as batch_op:
        batch_op.drop_index("ix_teams_version_pk_validity")
        batch_op.drop_index("ix_teams_version_pk_transaction_id")

    with op.batch_alter_table("roles_version", schema=None) as batch_op:
        batch_op.drop_index("ix_roles_version_pk_validity")
        batch_op.drop_index("ix_roles_version_pk_transaction_id")

    with op.batch_alter_table("projects_version", schema=None) as batch_op:
        batch_op.drop_index("ix_projects_version_pk_validity")
        batch_op.drop_index("ix_projects_version_pk_transaction_id")

    with op.batch_alter_table("project_environments_version", schema=None) as batch_op:
        batch_op.drop_index("ix_project_environments_version_pk_validity")
        batch_op.drop_index("ix_project_environments_version_pk_transaction_id")

    with op.batch_alter_table(
        "project_environment_configurations_version", schema=None
    ) as batch_op:
        batch_op.drop_index("ix_project_environment_configurations_version_pk_validity")
        batch_op.drop_index(
            "ix_project_environment_configurations_version_pk_transaction_id"
        )

    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.drop_index("ix_project_applications_version_pk_validity")
        batch_op.drop_index("ix_project_applications_version_pk_transaction_id")

    with op.batch_alter_table("project_app_releases_version", schema=None) as batch_op:
        batch_op.drop_index("ix_project_app_releases_version_pk_validity")
        batch_op.drop_index("ix_project_app_releases_version_pk_transaction_id")

    with op.batch_alter_table("project_app_images_version", schema=None) as batch_op:
        batch_op.drop_index("ix_project_app_images_version_pk_validity")
        batch_op.drop_index("ix_project_app_images_version_pk_transaction_id")

    with op.batch_alter_table(
        "project_app_configurations_version", schema=None
    ) as batch_op:
        batch_op.drop_index("ix_project_app_configurations_version_pk_validity")
        batch_op.drop_index("ix_project_app_configurations_version_pk_transaction_id")

    with op.batch_alter_table("organizations_version", schema=None) as batch_op:
        batch_op.drop_index("ix_organizations_version_pk_validity")
        batch_op.drop_index("ix_organizations_version_pk_transaction_id")

    with op.batch_alter_table("ingresses_version", schema=None) as batch_op:
        batch_op.drop_index("ix_ingresses_version_pk_validity")
        batch_op.drop_index("ix_ingresses_version_pk_transaction_id")

    with op.batch_alter_table("ingress_paths_version", schema=None) as batch_op:
        batch_op.drop_index("ix_ingress_paths_version_pk_validity")
        batch_op.drop_index("ix_ingress_paths_version_pk_transaction_id")

    with op.batch_alter_table("ingress_hosts_version", schema=None) as batch_op:
        batch_op.drop_index("ix_ingress_hosts_version_pk_validity")
        batch_op.drop_index("ix_ingress_hosts_version_pk_transaction_id")

    with op.batch_alter_table("hooks_version", schema=None) as batch_op:
        batch_op.drop_index("ix_hooks_version_pk_validity")
        batch_op.drop_index("ix_hooks_version_pk_transaction_id")

    with op.batch_alter_table("deployments_version", schema=None) as batch_op:
        batch_op.drop_index("ix_deployments_version_pk_validity")
        batch_op.drop_index("ix_deployments_version_pk_transaction_id")

    with op.batch_alter_table(
        "application_environments_version", schema=None
    ) as batch_op:
        batch_op.drop_index("ix_application_environments_version_pk_validity")
        batch_op.drop_index("ix_application_environments_version_pk_transaction_id")

    # ### end Alembic commands ###
