"""empty message

Revision ID: a645df168b55
Revises: 453e45653299
Create Date: 2018-03-14 21:35:17.841685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a645df168b55'
down_revision = '453e45653299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_applications', sa.Column('github_app_installation_id', sa.Integer(), nullable=True))
    op.add_column('project_applications_version', sa.Column('github_app_installation_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_applications_version', 'github_app_installation_id')
    op.drop_column('project_applications', 'github_app_installation_id')
    # ### end Alembic commands ###
