"""add ingress tables

Revision ID: a95f942c7d60
Revises: f14c2b6be159
Create Date: 2026-03-05 18:48:04.607600

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a95f942c7d60"
down_revision = "f14c2b6be159"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingress_hosts_version",
        sa.Column("created", sa.DateTime(), autoincrement=False, nullable=False),
        sa.Column("updated", sa.DateTime(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ingress_id",
            postgresql.UUID(as_uuid=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "hostname", sa.String(length=253), autoincrement=False, nullable=False
        ),
        sa.Column("tls_enabled", sa.Boolean(), autoincrement=False, nullable=False),
        sa.Column(
            "is_auto_generated", sa.Boolean(), autoincrement=False, nullable=False
        ),
        sa.Column("version_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", "transaction_id", name=op.f("pk_ingress_hosts_version")
        ),
    )
    op.create_index(
        op.f("ix_ingress_hosts_version_end_transaction_id"),
        "ingress_hosts_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingress_hosts_version_ingress_id"),
        "ingress_hosts_version",
        ["ingress_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingress_hosts_version_operation_type"),
        "ingress_hosts_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingress_hosts_version_transaction_id"),
        "ingress_hosts_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "ingress_paths_version",
        sa.Column("created", sa.DateTime(), autoincrement=False, nullable=False),
        sa.Column("updated", sa.DateTime(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ingress_id",
            postgresql.UUID(as_uuid=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("path", sa.String(length=256), autoincrement=False, nullable=False),
        sa.Column(
            "path_type", sa.String(length=32), autoincrement=False, nullable=False
        ),
        sa.Column(
            "target_process_name",
            sa.String(length=64),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("version_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", "transaction_id", name=op.f("pk_ingress_paths_version")
        ),
    )
    op.create_index(
        op.f("ix_ingress_paths_version_end_transaction_id"),
        "ingress_paths_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingress_paths_version_ingress_id"),
        "ingress_paths_version",
        ["ingress_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingress_paths_version_operation_type"),
        "ingress_paths_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingress_paths_version_transaction_id"),
        "ingress_paths_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "ingresses_version",
        sa.Column("created", sa.DateTime(), autoincrement=False, nullable=False),
        sa.Column("updated", sa.DateTime(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "application_environment_id",
            postgresql.UUID(as_uuid=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.String(length=64), autoincrement=False, nullable=False),
        sa.Column("enabled", sa.Boolean(), autoincrement=False, nullable=False),
        sa.Column(
            "ingress_class_name",
            sa.String(length=64),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "backend_protocol",
            sa.String(length=16),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "proxy_connect_timeout",
            sa.String(length=16),
            server_default="10s",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "proxy_read_timeout",
            sa.String(length=16),
            server_default="10s",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "proxy_send_timeout",
            sa.String(length=16),
            server_default="10s",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "proxy_body_size",
            sa.String(length=16),
            server_default="10M",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "client_body_buffer_size",
            sa.String(length=16),
            server_default="1M",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "proxy_request_buffering",
            sa.String(length=16),
            server_default="on",
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "session_affinity", sa.Boolean(), autoincrement=False, nullable=False
        ),
        sa.Column("use_regex", sa.Boolean(), autoincrement=False, nullable=False),
        sa.Column(
            "allow_annotations", sa.Boolean(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "extra_annotations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "cluster_issuer", sa.String(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "force_ssl_redirect", sa.Boolean(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "service_upstream", sa.Boolean(), autoincrement=False, nullable=False
        ),
        sa.Column("version_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", "transaction_id", name=op.f("pk_ingresses_version")
        ),
    )
    op.create_index(
        op.f("ix_ingresses_version_application_environment_id"),
        "ingresses_version",
        ["application_environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingresses_version_end_transaction_id"),
        "ingresses_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingresses_version_operation_type"),
        "ingresses_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingresses_version_transaction_id"),
        "ingresses_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "ingresses",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "application_environment_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("ingress_class_name", sa.String(length=64), nullable=False),
        sa.Column("backend_protocol", sa.String(length=16), nullable=False),
        sa.Column(
            "proxy_connect_timeout",
            sa.String(length=16),
            server_default="10s",
            nullable=True,
        ),
        sa.Column(
            "proxy_read_timeout",
            sa.String(length=16),
            server_default="10s",
            nullable=True,
        ),
        sa.Column(
            "proxy_send_timeout",
            sa.String(length=16),
            server_default="10s",
            nullable=True,
        ),
        sa.Column(
            "proxy_body_size", sa.String(length=16), server_default="10M", nullable=True
        ),
        sa.Column(
            "client_body_buffer_size",
            sa.String(length=16),
            server_default="1M",
            nullable=True,
        ),
        sa.Column(
            "proxy_request_buffering",
            sa.String(length=16),
            server_default="on",
            nullable=True,
        ),
        sa.Column("session_affinity", sa.Boolean(), nullable=False),
        sa.Column("use_regex", sa.Boolean(), nullable=False),
        sa.Column("allow_annotations", sa.Boolean(), nullable=False),
        sa.Column(
            "extra_annotations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("cluster_issuer", sa.String(length=64), nullable=False),
        sa.Column("force_ssl_redirect", sa.Boolean(), nullable=False),
        sa.Column("service_upstream", sa.Boolean(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_environment_id"],
            ["application_environments.id"],
            name=op.f(
                "fk_ingresses_application_environment_id_application_environments"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingresses")),
        sa.UniqueConstraint(
            "application_environment_id",
            "name",
            name=op.f("uq_ingresses_application_environment_id"),
        ),
    )
    op.create_index(
        op.f("ix_ingresses_application_environment_id"),
        "ingresses",
        ["application_environment_id"],
        unique=False,
    )
    op.create_table(
        "ingress_hosts",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("ingress_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("hostname", sa.String(length=253), nullable=False),
        sa.Column("tls_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_auto_generated", sa.Boolean(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingress_id"],
            ["ingresses.id"],
            name=op.f("fk_ingress_hosts_ingress_id_ingresses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingress_hosts")),
    )
    op.create_index(
        "ix_ingress_hosts_hostname_unique",
        "ingress_hosts",
        ["hostname"],
        unique=True,
        postgresql_where=sa.text("NOT is_auto_generated"),
    )
    op.create_index(
        op.f("ix_ingress_hosts_ingress_id"),
        "ingress_hosts",
        ["ingress_id"],
        unique=False,
    )
    op.create_table(
        "ingress_paths",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("ingress_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("path_type", sa.String(length=32), nullable=False),
        sa.Column("target_process_name", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingress_id"],
            ["ingresses.id"],
            name=op.f("fk_ingress_paths_ingress_id_ingresses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingress_paths")),
        sa.UniqueConstraint(
            "ingress_id", "path", name=op.f("uq_ingress_paths_ingress_id")
        ),
    )
    op.create_index(
        op.f("ix_ingress_paths_ingress_id"),
        "ingress_paths",
        ["ingress_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingress_paths_ingress_id"), table_name="ingress_paths")
    op.drop_table("ingress_paths")
    op.drop_index(op.f("ix_ingress_hosts_ingress_id"), table_name="ingress_hosts")
    op.drop_index(
        "ix_ingress_hosts_hostname_unique",
        table_name="ingress_hosts",
        postgresql_where=sa.text("NOT is_auto_generated"),
    )
    op.drop_table("ingress_hosts")
    op.drop_index(
        op.f("ix_ingresses_application_environment_id"), table_name="ingresses"
    )
    op.drop_table("ingresses")
    op.drop_index(
        op.f("ix_ingresses_version_transaction_id"), table_name="ingresses_version"
    )
    op.drop_index(
        op.f("ix_ingresses_version_operation_type"), table_name="ingresses_version"
    )
    op.drop_index(
        op.f("ix_ingresses_version_end_transaction_id"), table_name="ingresses_version"
    )
    op.drop_index(
        op.f("ix_ingresses_version_application_environment_id"),
        table_name="ingresses_version",
    )
    op.drop_table("ingresses_version")
    op.drop_index(
        op.f("ix_ingress_paths_version_transaction_id"),
        table_name="ingress_paths_version",
    )
    op.drop_index(
        op.f("ix_ingress_paths_version_operation_type"),
        table_name="ingress_paths_version",
    )
    op.drop_index(
        op.f("ix_ingress_paths_version_ingress_id"), table_name="ingress_paths_version"
    )
    op.drop_index(
        op.f("ix_ingress_paths_version_end_transaction_id"),
        table_name="ingress_paths_version",
    )
    op.drop_table("ingress_paths_version")
    op.drop_index(
        op.f("ix_ingress_hosts_version_transaction_id"),
        table_name="ingress_hosts_version",
    )
    op.drop_index(
        op.f("ix_ingress_hosts_version_operation_type"),
        table_name="ingress_hosts_version",
    )
    op.drop_index(
        op.f("ix_ingress_hosts_version_ingress_id"), table_name="ingress_hosts_version"
    )
    op.drop_index(
        op.f("ix_ingress_hosts_version_end_transaction_id"),
        table_name="ingress_hosts_version",
    )
    op.drop_table("ingress_hosts_version")
    # ### end Alembic commands ###
