"""add_secret_fingerprint_to_environment_configurations

Revision ID: aa90a43a1737
Revises: 3d08438ad713
Create Date: 2026-04-18 12:29:09.300019

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aa90a43a1737"
down_revision = "3d08438ad713"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "project_environment_configurations", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("secret_fingerprint", sa.Text(), nullable=True))

    with op.batch_alter_table(
        "project_environment_configurations_version", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "secret_fingerprint", sa.Text(), autoincrement=False, nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "project_environment_configurations_version", schema=None
    ) as batch_op:
        batch_op.drop_column("secret_fingerprint")

    with op.batch_alter_table(
        "project_environment_configurations", schema=None
    ) as batch_op:
        batch_op.drop_column("secret_fingerprint")

    # ### end Alembic commands ###
