"""

Revision ID: ad862ed80733
Revises: db9d51e1234b
Create Date: 2026-03-10 00:18:33.715045

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad862ed80733"
down_revision = "db9d51e1234b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_application_environments_application_id",
        "application_environments",
        type_="unique",
    )
    op.create_index(
        "uq_app_env_active",
        "application_environments",
        ["application_id", "environment_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_app_env_active",
        table_name="application_environments",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_unique_constraint(
        "uq_application_environments_application_id",
        "application_environments",
        ["application_id", "environment_id"],
    )
    # ### end Alembic commands ###
