"""empty message

Revision ID: b3f0127e1ce2
Revises: 6b6caf399b71
Create Date: 2023-02-11 15:34:36.889728

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b3f0127e1ce2"
down_revision = "6b6caf399b71"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hooks", sa.Column("deployed", sa.Boolean(), nullable=True))
    op.add_column(
        "hooks_version",
        sa.Column("deployed", sa.Boolean(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hooks_version", "deployed")
    op.drop_column("hooks", "deployed")
    # ### end Alembic commands ###
