"""empty message

Revision ID: c02527606e42
Revises: 732af5abd4a6
Create Date: 2023-02-20 16:33:55.227805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02527606e42'
down_revision = '732af5abd4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_app_images', sa.Column('build_ref', sa.String(length=1024), nullable=True))
    op.alter_column('project_app_images', 'build_slug',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.add_column('project_app_images_version', sa.Column('build_ref', sa.String(length=1024), autoincrement=False, nullable=True))
    op.create_check_constraint('image_has_build_target', table_name='project_app_images', condition='NOT(build_ref IS NULL AND build_slug IS NULL)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_has_build_target')
    op.drop_column('project_app_images_version', 'build_ref')
    op.alter_column('project_app_images', 'build_slug',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('project_app_images', 'build_ref')
    # ### end Alembic commands ###
