"""empty message

Revision ID: c8fe63844dd6
Revises: c02527606e42
Create Date: 2023-02-23 02:10:16.038406

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8fe63844dd6"
down_revision = "c02527606e42"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_app_images",
        sa.Column("build_job_id", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "project_app_images_version",
        sa.Column(
            "build_job_id", sa.String(length=64), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_app_images_version", "build_job_id")
    op.drop_column("project_app_images", "build_job_id")
    # ### end Alembic commands ###
