"""add billing

Revision ID: da279f657734
Revises: 88f230545618
Create Date: 2026-03-21 15:57:01.530629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da279f657734'
down_revision = '88f230545618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_version',
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_customer_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('stripe_sub_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('stripe_sub_status', sa.String(), autoincrement=False, nullable=True),
    sa.Column('stripe_sub_plan', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('org_id', 'transaction_id', name=op.f('pk_billing_version'))
    )
    with op.batch_alter_table('billing_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_billing_version_pk_transaction_id', ['org_id', sa.text('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_billing_version_pk_validity', ['org_id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_version_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_version_stripe_sub_id'), ['stripe_sub_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('billing_webhook_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_webhook_events'))
    )
    with op.batch_alter_table('billing_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_webhook_events_stripe_event_id'), ['stripe_event_id'], unique=True)

    op.create_table('billing_webhook_events_version',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('stripe_event_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.String(), autoincrement=False, nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_billing_webhook_events_version'))
    )
    with op.batch_alter_table('billing_webhook_events_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_webhook_events_version_end_transaction_id'), ['end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_webhook_events_version_operation_type'), ['operation_type'], unique=False)
        batch_op.create_index('ix_billing_webhook_events_version_pk_transaction_id', ['id', sa.text('transaction_id DESC')], unique=False)
        batch_op.create_index('ix_billing_webhook_events_version_pk_validity', ['id', 'transaction_id', 'end_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_webhook_events_version_stripe_event_id'), ['stripe_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_webhook_events_version_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('billing',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_sub_id', sa.String(), nullable=True),
    sa.Column('stripe_sub_status', sa.String(), nullable=True),
    sa.Column('stripe_sub_plan', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_billing_org_id_organizations')),
    sa.PrimaryKeyConstraint('org_id', name=op.f('pk_billing'))
    )
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_stripe_customer_id'), ['stripe_customer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_billing_stripe_sub_id'), ['stripe_sub_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_stripe_sub_id'))
        batch_op.drop_index(batch_op.f('ix_billing_stripe_customer_id'))

    op.drop_table('billing')
    with op.batch_alter_table('billing_webhook_events_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_webhook_events_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_billing_webhook_events_version_stripe_event_id'))
        batch_op.drop_index('ix_billing_webhook_events_version_pk_validity')
        batch_op.drop_index('ix_billing_webhook_events_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_billing_webhook_events_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_billing_webhook_events_version_end_transaction_id'))

    op.drop_table('billing_webhook_events_version')
    with op.batch_alter_table('billing_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_webhook_events_stripe_event_id'))

    op.drop_table('billing_webhook_events')
    with op.batch_alter_table('billing_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_version_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_billing_version_stripe_sub_id'))
        batch_op.drop_index(batch_op.f('ix_billing_version_stripe_customer_id'))
        batch_op.drop_index('ix_billing_version_pk_validity')
        batch_op.drop_index('ix_billing_version_pk_transaction_id')
        batch_op.drop_index(batch_op.f('ix_billing_version_operation_type'))
        batch_op.drop_index(batch_op.f('ix_billing_version_end_transaction_id'))

    op.drop_table('billing_version')
    # ### end Alembic commands ###
