"""

Revision ID: dd222c33058e
Revises: e5f9a2c7d834
Create Date: 2026-03-14 13:52:25.623710

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "dd222c33058e"
down_revision = "e5f9a2c7d834"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_environments",
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
    )
    op.drop_constraint(
        "uq_application_environments_application_id",
        "application_environments",
        type_="unique",
    )
    op.create_index(
        op.f("ix_application_environments_deleted_at"),
        "application_environments",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "uq_app_env_active",
        "application_environments",
        ["application_id", "environment_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.add_column(
        "application_environments_version",
        sa.Column("deleted_at", sa.DateTime(), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_application_environments_version_deleted_at"),
        "application_environments_version",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "organizations", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.create_index(
        op.f("ix_organizations_deleted_at"),
        "organizations",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "organizations_version",
        sa.Column("deleted_at", sa.DateTime(), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_organizations_version_deleted_at"),
        "organizations_version",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "project_applications", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.create_index(
        op.f("ix_project_applications_deleted_at"),
        "project_applications",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "project_applications_version",
        sa.Column("deleted_at", sa.DateTime(), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_project_applications_version_deleted_at"),
        "project_applications_version",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "project_environments", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.create_index(
        op.f("ix_project_environments_deleted_at"),
        "project_environments",
        ["deleted_at"],
        unique=False,
    )
    op.add_column(
        "project_environments_version",
        sa.Column("deleted_at", sa.DateTime(), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_project_environments_version_deleted_at"),
        "project_environments_version",
        ["deleted_at"],
        unique=False,
    )
    op.add_column("projects", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_projects_deleted_at"), "projects", ["deleted_at"], unique=False
    )
    op.add_column(
        "projects_version",
        sa.Column("deleted_at", sa.DateTime(), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_projects_version_deleted_at"),
        "projects_version",
        ["deleted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_version_deleted_at"), table_name="projects_version")
    op.drop_column("projects_version", "deleted_at")
    op.drop_index(op.f("ix_projects_deleted_at"), table_name="projects")
    op.drop_column("projects", "deleted_at")
    op.drop_index(
        op.f("ix_project_environments_version_deleted_at"),
        table_name="project_environments_version",
    )
    op.drop_column("project_environments_version", "deleted_at")
    op.drop_index(
        op.f("ix_project_environments_deleted_at"), table_name="project_environments"
    )
    op.drop_column("project_environments", "deleted_at")
    op.drop_index(
        op.f("ix_project_applications_version_deleted_at"),
        table_name="project_applications_version",
    )
    op.drop_column("project_applications_version", "deleted_at")
    op.drop_index(
        op.f("ix_project_applications_deleted_at"), table_name="project_applications"
    )
    op.drop_column("project_applications", "deleted_at")
    op.drop_index(
        op.f("ix_organizations_version_deleted_at"), table_name="organizations_version"
    )
    op.drop_column("organizations_version", "deleted_at")
    op.drop_index(op.f("ix_organizations_deleted_at"), table_name="organizations")
    op.drop_column("organizations", "deleted_at")
    op.drop_index(
        op.f("ix_application_environments_version_deleted_at"),
        table_name="application_environments_version",
    )
    op.drop_column("application_environments_version", "deleted_at")
    op.drop_index(
        "uq_app_env_active",
        table_name="application_environments",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_application_environments_deleted_at"),
        table_name="application_environments",
    )
    op.create_unique_constraint(
        "uq_application_environments_application_id",
        "application_environments",
        ["application_id", "environment_id"],
    )
    op.drop_column("application_environments", "deleted_at")
    # ### end Alembic commands ###
