"""add webauthn table

Revision ID: e2010e459bdc
Revises: f0735497b1aa
Create Date: 2026-03-19 11:50:35.195447

"""

from alembic import op
import flask_security
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e2010e459bdc"
down_revision = "f0735497b1aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webauthn",
        sa.Column("credential_id", sa.LargeBinary(length=1024), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=True),
        sa.Column("transports", flask_security.datastore.AsaList(), nullable=True),
        sa.Column("backup_state", sa.Boolean(), nullable=False),
        sa.Column("device_type", sa.String(length=64), nullable=False),
        sa.Column("extensions", sa.String(length=255), nullable=True),
        sa.Column(
            "create_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lastuse_datetime", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("usage", sa.String(length=64), nullable=False),
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_webauthn_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webauthn")),
    )
    op.create_index(
        op.f("ix_webauthn_credential_id"), "webauthn", ["credential_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webauthn_credential_id"), table_name="webauthn")
    op.drop_table("webauthn")
    # ### end Alembic commands ###
