"""add service_version to resources

Revision ID: e52e2a058fc3
Revises: 7e334b3e2b87
Create Date: 2026-04-12 18:53:52.860980

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e52e2a058fc3"
down_revision = "7e334b3e2b87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resources", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "service_version",
                sa.String(length=16),
                nullable=False,
                server_default="18",
            )
        )

    # Backfill: Redis resources should default to version "8"
    op.execute(
        sa.text("UPDATE resources SET service_version = '8' WHERE type = 'redis'")
    )

    with op.batch_alter_table("resources_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "service_version",
                sa.String(length=16),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resources_version", schema=None) as batch_op:
        batch_op.drop_column("service_version")

    with op.batch_alter_table("resources", schema=None) as batch_op:
        batch_op.drop_column("service_version")

    # ### end Alembic commands ###
