"""job_logs unique on job_name and namespace

Revision ID: e701c9f5de37
Revises: 7a4a29016eed
Create Date: 2026-03-27 19:29:26.206567

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "e701c9f5de37"
down_revision = "7a4a29016eed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_logs", schema=None) as batch_op:
        batch_op.drop_constraint("uq_job_logs_job_name", type_="unique")
        batch_op.create_unique_constraint(
            "uq_job_logs_job_name_namespace", ["job_name", "namespace"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_logs", schema=None) as batch_op:
        batch_op.drop_constraint("uq_job_logs_job_name_namespace", type_="unique")
        batch_op.create_unique_constraint(
            "uq_job_logs_job_name", ["job_name"], postgresql_nulls_not_distinct=False
        )

    # ### end Alembic commands ###
