"""add forked_from_environment_id

Revision ID: f14c2b6be159
Revises: 111eac3110be
Create Date: 2026-03-04 22:55:55.856707

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f14c2b6be159"
down_revision = "111eac3110be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_environments",
        sa.Column(
            "forked_from_environment_id", postgresql.UUID(as_uuid=True), nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("fk_project_environments_forked_from_environment_id_project_environments"),
        "project_environments",
        "project_environments",
        ["forked_from_environment_id"],
        ["id"],
    )
    op.add_column(
        "project_environments_version",
        sa.Column(
            "forked_from_environment_id",
            postgresql.UUID(as_uuid=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_environments_version", "forked_from_environment_id")
    op.drop_constraint(
        op.f("fk_project_environments_forked_from_environment_id_project_environments"),
        "project_environments",
        type_="foreignkey",
    )
    op.drop_column("project_environments", "forked_from_environment_id")
    # ### end Alembic commands ###
