"""adjust auto_deploy_wait_for_ci

Revision ID: f40dfa811074
Revises: 14f8def5bd0d
Create Date: 2026-03-19 21:32:26.924809

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f40dfa811074"
down_revision = "14f8def5bd0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Backfill NULLs before setting NOT NULL
    op.execute(
        "UPDATE application_environments SET auto_deploy_wait_for_ci = true WHERE auto_deploy_wait_for_ci IS NULL"
    )
    with op.batch_alter_table("application_environments", schema=None) as batch_op:
        batch_op.alter_column(
            "auto_deploy_wait_for_ci",
            existing_type=sa.BOOLEAN(),
            server_default="true",
            nullable=False,
        )

    with op.batch_alter_table("project_applications", schema=None) as batch_op:
        batch_op.drop_column("auto_deploy_wait_for_ci")

    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.drop_column("auto_deploy_wait_for_ci")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_applications_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "auto_deploy_wait_for_ci",
                sa.BOOLEAN(),
                server_default=sa.text("true"),
                autoincrement=False,
                nullable=True,
            )
        )

    with op.batch_alter_table("project_applications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "auto_deploy_wait_for_ci",
                sa.BOOLEAN(),
                server_default=sa.text("true"),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("application_environments", schema=None) as batch_op:
        batch_op.alter_column(
            "auto_deploy_wait_for_ci", existing_type=sa.BOOLEAN(), nullable=True
        )

    # ### end Alembic commands ###
