"""drop redundant version_id from resource subtypes

Revision ID: f7ba2e49c737
Revises: c2d5d53ebd73
Create Date: 2026-04-12 16:34:34.858070

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7ba2e49c737"
down_revision = "c2d5d53ebd73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resources_postgres", schema=None) as batch_op:
        batch_op.drop_column("version_id")

    with op.batch_alter_table("resources_postgres_version", schema=None) as batch_op:
        batch_op.drop_column("version_id")

    with op.batch_alter_table("resources_redis", schema=None) as batch_op:
        batch_op.drop_column("version_id")

    with op.batch_alter_table("resources_redis_version", schema=None) as batch_op:
        batch_op.drop_column("version_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resources_redis_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("resources_redis", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )

    with op.batch_alter_table("resources_postgres_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("resources_postgres", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("version_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
