"""empty message

Revision ID: fb54812c13a1
Revises: 7be3d140b38b
Create Date: 2018-03-14 11:38:52.660720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb54812c13a1'
down_revision = '7be3d140b38b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('deploy_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('deployments_version', sa.Column('deploy_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments_version', 'deploy_metadata')
    op.drop_column('deployments', 'deploy_metadata')
    # ### end Alembic commands ###
