"""add job_logs lookup index

Revision ID: fe51fd85dbe5
Revises: 7a4a29016eed
Create Date: 2026-03-27 19:34:44.191490

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "fe51fd85dbe5"
down_revision = "7a4a29016eed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_logs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_job_logs_app_env_process_completion",
            [
                "application_id",
                "application_environment_id",
                "process_name",
                sa.text("completion_time DESC"),
            ],
            unique=False,
        )
        batch_op.create_unique_constraint(
            "uq_job_logs_job_name_namespace", ["job_name", "namespace"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_logs", schema=None) as batch_op:
        batch_op.drop_constraint("uq_job_logs_job_name_namespace", type_="unique")
        batch_op.drop_index("ix_job_logs_app_env_process_completion")

    # ### end Alembic commands ###
