FROM alpine:3.7

COPY Procfile /Procfile

ARG BUILD_TESTING
ARG BUILD_TESTING_SECURE
ARG TESTING
ARG TESTING_SECURE

RUN apk update
RUN apk add bash

RUN echo $BUILD_TESTING
RUN echo $BUILD_TESTING_SECURE
RUN echo $TESTING
RUN echo $TESTING_SECURE
