name: CI
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        include:
          - name: Lint
            command: make lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Run ${{ matrix.name }}
      run: ${{ matrix.command }}
