name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Lint
            command: make lint
          - name: Type-Check
            command: make type-check
          - name: Security-Check
            command: make security-check
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v3
      - name: Run ${{ matrix.name }}
        run: ${{ matrix.command }}
